### ISSUE TITLE
User-Agent에서 headless탐지해서 막히는 이슈

### ISSUE THREAD

**Issue by Kim-tang2** [O-Seonsik/O-s-selenium-builder#1]
몇몇 서버에서 User-Agent에 headless를 탐지해서 막아버리는 이슈가 있습니다.

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36
이게 일반적인 크롬 User-Agent값이고

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) HeadlessChrome/87.0.4280.88 Safari/537.36
headless는 이런 User-Agent값을 가지고 있을 겁니다.

chrome_options.add_argument('Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 ')

chrome options에 Chrome으로 던져주면 서버에서 헤드리스라고 해서 막진 않을 것 같습니다. 😘

**Comment by Kim-tang2** [comment]
https://intoli.com/blog/making-chrome-headless-undetectable/chrome-headless-test.html

해당 웹페이지에서 User Agent값 쉽게 볼 수 있습니다. 도움이 되었으면 좋겠습니다.

**Comment by O-Seonsik** [comment]
이슈 남겨주셔서 감사합니다. 좋은 정보이고 유익한 정보임은 확실합니다. 그러나 해당 Repository는 README.md에 작성했듯 단순히  shell script를 통해 selenium코드를 build할 수 있는 환경을 자동으로 완성해주는 shell file이 주 목적입니다. python 실행파일은 설정이 잘 되었는지 확인하는 코드일 뿐입니다. 따라서 해당 issue를 여기에 남겨주신 이유를 잘 모르겠습니다. 😂

**Comment by Kim-tang2** [comment]
FAN 학회분들이 추후 환경 세팅되고 크롤링 과정중 문제가 발생할 것을 염두하여 이슈 남겼습니다. 저도 학부 학술동아리에서 기획부서를 맡고 있어서 이런 상황이 종종 발생되어 괜한 오지랖에 선식님의 노동소요를 줄여드리고자 이슈 작성했습니다. 😥  이슈를 남긴 목적을 기재하지 않아 혼란을 드린점 죄송합니다. 이슈는 닫겠습니다.
